name: pr
on: [pull_request]
jobs:
  test:
    name: 'Node ${{ matrix.node }}, React ${{ matrix.react }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
        react: [17, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          yarn install --frozen-lockfile
          yarn test:ci
          yarn build
        env:
          REACTJS_VERSION: ${{ matrix.react }}
      - run: yarn test:size
        if: matrix.node == '16' && matrix.react == '18'
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
